// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx2nIRAXW4rkmNe18hDRzDHVlYX2rd7yI',
    appId: '1:283403520293:web:191970601c4f4790e2f2cc',
    messagingSenderId: '283403520293',
    projectId: 'dawer-prod',
    authDomain: 'dawer-prod.firebaseapp.com',
    storageBucket: 'dawer-prod.firebasestorage.app',
    measurementId: 'G-G6J775MDW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfR0PD0yckHx8Nm14OKL9ZH8MmaG-kEYg',
    appId: '1:283403520293:android:b14597ce12d4cae5e2f2cc',
    messagingSenderId: '283403520293',
    projectId: 'dawer-prod',
    storageBucket: 'dawer-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBflFn6n04M8M4jF9HS8EtVPv6Rjngx7D0',
    appId: '1:283403520293:ios:13e0a62a3e624282e2f2cc',
    messagingSenderId: '283403520293',
    projectId: 'dawer-prod',
    storageBucket: 'dawer-prod.firebasestorage.app',
    iosBundleId: 'com.example.dwaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBflFn6n04M8M4jF9HS8EtVPv6Rjngx7D0',
    appId: '1:283403520293:ios:13e0a62a3e624282e2f2cc',
    messagingSenderId: '283403520293',
    projectId: 'dawer-prod',
    storageBucket: 'dawer-prod.firebasestorage.app',
    iosBundleId: 'com.example.dwaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx2nIRAXW4rkmNe18hDRzDHVlYX2rd7yI',
    appId: '1:283403520293:web:873ea3021b93854ae2f2cc',
    messagingSenderId: '283403520293',
    projectId: 'dawer-prod',
    authDomain: 'dawer-prod.firebaseapp.com',
    storageBucket: 'dawer-prod.firebasestorage.app',
    measurementId: 'G-NDDPHQK779',
  );
}
