import 'package:supabase_flutter/supabase_flutter.dart';

import '../../core/result/result.dart';
import '../../data/models/chat_message_supabase_ext.dart';
import '../../data/models/user_role.dart';
import '../../domain/chat/entities/chat_message.dart';
import '../../domain/chat/repositories/i_chat_repository.dart';
import '../../domain/failures/app_failure.dart';

/// Supabase-backed implementation of [IChatRepository].
///
/// Order-scoped chat: one room per order, `room_id == orders.id`. Participants
/// are the order's parties (supplier / driver / recycling company); RLS on
/// `chat_messages` enforces that (migration `00003_chat.sql`).
///
/// Realtime: `watchMessages` uses `.from('chat_messages').stream(...)` which is
/// Supabase Realtime under the hood — a new INSERT or an UPDATE to `is_read`
/// pushes a fresh snapshot to every subscriber on the order. This is the
/// MVP-grade equivalent of the design doc's `order:{id}` fan-out channel.
///
/// See `docs/architecture-decisions/backend-strategy.md`.
class SupabaseChatRepository implements IChatRepository {
  SupabaseChatRepository(this._client);

  final SupabaseClient _client;

  @override
  Stream<List<ChatMessage>> watchMessages(String orderId) {
    return _client
        .from('chat_messages')
        .stream(primaryKey: const ['id'])
        .eq('room_id', orderId)
        .order('sent_at', ascending: true)
        .map((rows) => rows.map(chatMessageFromSupabaseJson).toList());
  }

  @override
  Future<AppResult<void>> sendMessage({
    required String orderId,
    required String senderId,
    required String senderName,
    required UserRole senderRole,
    required String content,
  }) {
    final trimmed = content.trim();
    if (trimmed.isEmpty) {
      return Future.value(
        const Failure(ValidationFailure(message: 'الرسالة فارغة')),
      );
    }

    final row = ChatMessage(
      id: '', // generated by Postgres (gen_random_uuid)
      roomId: orderId,
      senderId: senderId,
      senderName: senderName,
      senderRole: senderRole,
      content: trimmed,
      sentAt: DateTime.now().toUtc(),
    ).toSupabaseMap();
    // Let Postgres set sent_at default for consistency across clients; remove
    // only if the caller's clock matters (it doesn't for ordering — DB is truth).
    row.remove('sent_at');
    row.remove('is_read');

    return _run(() => _client.from('chat_messages').insert(row));
  }

  @override
  Future<AppResult<void>> markRead(String orderId, String userId) {
    // Mark every message NOT sent by [userId] as read. Uses Postgres `neq` so
    // a single round-trip updates the whole room.
    //
    // Realtime loop note: this UPDATE fires a realtime event that re-renders
    // the list, but the second pass finds nothing left to flip, so it converges
    // in one cycle (not infinite). The mock avoided re-emitting; here the DB is
    // the source of truth so a single reconciliation render is correct.
    return _run(() => _client
        .from('chat_messages')
        .update({'is_read': true})
        .eq('room_id', orderId)
        .neq('sender_id', userId)
        .eq('is_read', false));
  }

  @override
  Future<int> unreadCount(String orderId, String userId) async {
    try {
      final res = await _client
          .from('chat_messages')
          .select('id')
          .eq('room_id', orderId)
          .neq('sender_id', userId)
          .eq('is_read', false)
          .count(CountOption.exact);
      return res.count;
    } catch (e) {
      // Best-effort: a failed count must not break the UI. Default to 0.
      return 0;
    }
  }

  // ── Internal ───────────────────────────────────────────────────────────────

  Future<AppResult<void>> _run(Future<void> Function() op) async {
    try {
      await op();
      return const Success(null);
    } on PostgrestException catch (e) {
      return Failure(UnknownFailure(message: e.message, code: e.code));
    } catch (e) {
      if (_isNetworkError(e)) {
        return const Failure(NetworkFailure());
      }
      return Failure(UnknownFailure.fromException(e));
    }
  }

  static bool _isNetworkError(Object e) {
    final msg = e.toString().toLowerCase();
    return msg.contains('socketexception') ||
        msg.contains('network') ||
        msg.contains('connection refused') ||
        msg.contains('failed host lookup');
  }
}
